version: '2'

services:
  mysql:
    image: daocloud.io/mysql
    container_name: mysql 
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: xxx 
        MYSQL_PASSWORD: xxx 
        MYSQL_ROOT_PASSWORD: xxx
    volumes:
        - /data/mysql:/var/lib/mysql
        # - /data/nagios/etc:/opt/nagios/etc
