version: '2'

services:
  mysql:
    image: daocloud.io/mysql
    container_name: mysql 
    network_mode: host
    restart: always
    #ports:
        #- 3307:3306
    environment:
        MYSQL_USER: xxx 
        MYSQL_PASSWORD: xxx 
        MYSQL_ROOT_PASSWORD: xxx
    volumes:
        - /data/mysql:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
        #- /var/run/docker-mysqld:/var/run/mysqld
        # - /data/nagios/etc:/opt/nagios/etc
